language: go
go:
  # - "1.14.x" At minimum the code should run make check on the latest two go versions in the default linux environment provided by Travis.
  - "1.14.x"

dist: xenial

addons:
  apt:
    packages:
      # For building MUSL static builds on Linux.
      - musl-tools
      #- gcc-mingw-w64-i686
      #- g++-mingw-w64-i686
      #- binutils-mingw-w64-i686
      #- libsnmp-dev

matrix:
  include:
    - os: linux
    - os: osx
      # Do not start osx build for PR
      if: type != pull_request
      osx_image: xcode8.3

before_install:
  - nvm install 10.16

install:
  - go get -u github.com/FiloSottile/vendorcheck
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin v1.31.0
  - make tidy

before_script:
  - ci_scripts/create-ip-aliases.sh

script:
  - make build
  - make test
  - make test-no-ci
  - make install-deps-ui
  - make lint-ui
  - make build-ui
